### PR TITLE
* [bug] Infinite loop reset if no conf.json file exists

### PR DESCRIPTION
**Pull request by snowyu**
This change is [Reviewable](https://reviewable.io/reviews/cesanta/mongoose-iot/123)

### CODE REVIEW

**Comment by alashkin** [comment]
File.loadJSON returns`undefined` on error
```
[32968/628] $ f = File.loadJSON("nofile.json")
undefined
[32944/604] $ f
undefined
```
And seems everything is OK.

Could you clarity the problem you faced and share steps to repro?

**Comment by snowyu** [comment]
1. Build firmware from source(make sure no conf.json file in your source) and burn it.
2. Enter Wifi.setup('WifiNetworkName', 'WifiPassword') on console to connect the internect.
3. The device has registered it to the clubby service successful.


```
fw 31924/484$ File.loadJSON('sdsdd')
{"message":"cannot open [sdsdd]"}
fw 32620/832$ 
```

Since 17 days passed. I will pull codes, and try again

**Comment by snowyu** [comment]
It's ok now. The loadJSON returns undefined now. I compares the codes from 823ca9d.

```patch
@@ -9797,7 +10172,9 @@ V7_PRIVATE enum v7_err File_loadJSON(struct v7 *v7, v7_val_t *res) {
     rcode = v7_parse_json_file(v7, file_name, res);
     if (rcode != V7_OK) {
       /* swallow exception and return undefined */
+      v7_clear_thrown_value(v7);
       rcode = V7_OK;
+      *res = v7_mk_undefined();
     }
   }
```

But, Why does the loadJSON change its return convention?

**Comment by mmikulicic** [comment]
the diff you are showing is actually a bug fix (3baeeda95e75549be01c324a735ba4289fb8bc7b).
that implemented the documented behaviour, see `/* swallow exception and return undefined */` above.

That commit actually fixes this very bug. The full root causes were:

1. our stack traces contained unbalanced quotes. The conf.json contains an error_message key containing the last error for reporting reasons. (fixed in 24b7529550a76395174ff192291261b2f7dee0ec and 0f3154454b17d6400999614212acf74a43cc71bd)
2. our File API is not throwing but it did throw

I noticed this issue independently and thus unfortunately @dimonomid and I didn't update this issue; sorry.

**Pull request closed without merging**
