### PR TITLE
Add fix for CoAP packet size calculation

### PR DESCRIPTION
**Pull request by iliapenev**
This change is [Reviewable](https://reviewable.io/reviews/cesanta/mongoose-iot/158)

### CODE REVIEW

**Comment by cpq** [comment]
@alashkin could you check this and integrate if correct, please?

**Comment by alashkin** [comment]
@iliapenev 

Hi!
Thanx for your fix.
Could you agree that you accept this: https://docs.cesanta.com/contributors_la.shtml ?

**Comment by iliapenev** [comment]
@alashkin  Agreement accepted.

**Comment by alashkin** [comment]
Integrated in https://github.com/cesanta/mongoose-iot/commit/ea721afd38fbca2ac65f032a194576659fd25b05

Thanx.

**Comment by iliapenev** [comment]
@alashkin 
https://github.com/cesanta/mongoose-iot/blob/master/mongoose/mongoose.c#L9781
This generates error when compiling
"/src//mongoose-iot/mongoose/mongoose.c", line 9781: error #69: integer conversion resulted in a change of sign

**Comment by alashkin** [comment]
what compiler/OS do you use?

**Comment by iliapenev** [comment]
Ubuntu 16.04
I'm compiling with docker image docker.cesanta.com/cc3200-build:1.2.0-r9

**Pull request closed without merging**
