### PR TITLE
Fix esp8266

### PR DESCRIPTION
**Pull request by iliapenev**
Fixes for this issues

ESP8266 Coap compile error #168 
ESP8266 fileno missing #163
ESP8266 MD5 #164

Theese errors appears with following flags
```
MG_ENABLE_JS = 0
MG_ENABLE_CLUBBY = 0
MG_ENABLE_HTTP_SSI = 0
MG_ENABLE_MQTT = 0

MG_FEATURES = \
    -DMG_DISABLE_JSON_RPC \
    -DMG_DISABLE_SYNC_RESOLVER \
    -DMG_DISABLE_SOCKETPAIR \
    -DMG_DISABLE_HTTP_KEEP_ALIVE \
    -DMG_DISABLE_DAV_AUTH \
    -DMG_DISABLE_CGI \
    -DMG_DISABLE_SSI \
    -DMG_DISABLE_DAV \
    -DMG_ENABLE_HTTP_STREAMING_MULTIPART \
    -DMG_NO_BSD_SOCKETS \
    -DMG_LOCALS \
    -DMG_FS_SPIFFS \
    -DMG_ENABLE_FILESYSTEM \
    -DDISABLE_C_CLUBBY \
-DMG_ENABLE_SSL
```

---
This change is [Reviewable](https://reviewable.io/reviews/cesanta/mongoose-iot/170)

### CODE REVIEW

**Comment by cpq** [comment]
@alashkin please integrate those!

**Comment by alashkin** [comment]
@cpq 
cannot be integrated "as is" because it breaks Windows build
Will fix

**Comment by alashkin** [comment]
Integrated in https://github.com/cesanta/mongoose-iot/commit/8a2d7910662fdff97dc053e72c10747a25814f8a

**Comment by iliapenev** [comment]
@alashkin 
Thanks but fileno is spelled wrong. 
"fineno(x)" should be "fileno"
Please check!

**Pull request closed without merging**
